[workspace]
channels = ["conda-forge", "bioconda"]
name = "web-template-analysis"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
streamlit = ">=1.51.0, <2"
pandas = ">=2.3.3, <3"
numpy = ">=2.3.4, <3"
seaborn = ">=0.13.2, <0.14"
matplotlib = ">=3.10.7, <4"
scipy = ">=1.16.3, <2"
